### ISSUE TITLE
This repository needs a license

### ISSUE THREAD

**Issue by lucas-ige** [ige-calcul/public-docs#31]
Users may want to reuse material (tutorials, computer code, etc.) from this repository for their own work. We should explicitly specify the conditions of such reuse. Yet I could not find any license in the repository. 

I suggest that, by default (case-by-case exceptions can be made):

- All the written material (tutorials, documentation, etc.) be licensed under the [Creative Commons Attribution 4.0 International (CC BY 4.0)](https://creativecommons.org/licenses/by/4.0/?ref=chooser-v1): people can reuse, modify, and redistribute the material, the only requirement being to cite the author (i.e. IGE).

- All the computer code be released under a very permissive licence, either the BSD 3-clause or the MIT license. Both allow users to reuse, modify, and redistribute the material, the only requirement being pretty much to cite the author. They are described [here](https://www.gnu.org/licenses/license-list.html).

Note that all the licenses mentioned above allow reuse of the material for commercial purposes.

Any thoughts or opinion?

**Comment by ekwaly** [comment]
I also recommend these two default licenses, as they are the most commonly used and the least complicated to handle.

**Comment by lucas-ige** [comment]
I created PR #32 to address this issue. I am not sure who to put as a reviewer though.
