### ISSUE TITLE
Here is the WRF and WRF-Chem how to run the model - basic training two exercises

### ISSUE THREAD

**Issue by jenniethomas** [ige-calcul/public-docs#42]
Paragraph:  The code and instructions for running either WRF or WRF-Chem with a specific setup are provided here.  The training workshop provided participants with a hands-on introduction to running the Weather Research and Forecasting (WRF) model and its chemistry extension, WRF-Chem, on the GridCad (Dahu) cluster. The documentation from the workshop provides the details of the technical setup, how to run simulations for a specific case (with specific options), and analyzing outputs.  All code and documentation are provided here on GitHub, providing a step-by-step guide for future model users to follow.

https://github.com/Regional-Modeling-LATMOS-IGE/WRF-Chem-training

**Comment by jenniethomas** [comment]
Can note Exercise 1 is for WRF and Exercise 2 is for WRF-Chem

**Comment by lucas-ige** [comment]
Created PR #54 to address this issue.

**Comment by lucas-ige** [comment]
PR #54 was merged. This issue is solved.
