### ISSUE TITLE
Here is the link to the GitLab of MAR version 3 

### ISSUE THREAD

**Issue by charlesamory** [ige-calcul/public-docs#45]
Paragraph: Download the code at the following link and find useful and documentation, instructions on how to install, prepare your setup and run the model on Dahu in the issues.

https://gitlab.com/Mar-Group/MARv3

**Comment by lucas-ige** [comment]
I added info about MAR in commits [f9404f8](https://github.com/ige-calcul/public-docs/commit/f9404f8b5bdd7d08cfd8e63a56ecb49a1c6bd8f0) and [70b3af9](https://github.com/ige-calcul/public-docs/commit/70b3af989b641c8d6c4522955f340c635e56371e). This issue is solved.
