### ISSUE TITLE
Add documentation on getting an account on TGCC

### ISSUE THREAD

**Issue by lucas-ige** [ige-calcul/public-docs#50]
The title says it all :)

**Comment by charlesamory** [comment]
to add : 
- downlad the form from the [DARI website](https://www.edari.fr). Any new account request requires that your collaborators first submit a request to be affiliated with your project. To assist you with this new process, documentation is available on the DARI website:
https://www.edari.fr/documentation/index.php/Documentation_compl%C3%A8te#ModalitesAccesCalculateurs
- provide an ip adress and setup a tunnel ssh though ssh.ige
- reach out to the IT department to fill and sign the form 
- take a look at the [TGCC documentation](https://www-hpc.cea.fr/tgcc-public/en/html/tgcc-public.html)

**Comment by lucas-ige** [comment]
I created PR #52 to address this issue.

**Comment by lucas-ige** [comment]
PR #52 was merged. This issue is solved.
